/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jwc.insta.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InstaSiteImages service. Represents a row in the &quot;JWC_InstaSiteImages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>jwc.insta.model.impl.InstaSiteImagesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>jwc.insta.model.impl.InstaSiteImagesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InstaSiteImages
 * @generated
 */
@ProviderType
public interface InstaSiteImagesModel extends BaseModel<InstaSiteImages> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a insta site images model instance should use the {@link InstaSiteImages} interface instead.
	 */

	/**
	 * Returns the primary key of this insta site images.
	 *
	 * @return the primary key of this insta site images
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this insta site images.
	 *
	 * @param primaryKey the primary key of this insta site images
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the insta site image ID of this insta site images.
	 *
	 * @return the insta site image ID of this insta site images
	 */
	public long getInstaSiteImageId();

	/**
	 * Sets the insta site image ID of this insta site images.
	 *
	 * @param instaSiteImageId the insta site image ID of this insta site images
	 */
	public void setInstaSiteImageId(long instaSiteImageId);

	/**
	 * Returns the page key of this insta site images.
	 *
	 * @return the page key of this insta site images
	 */
	@AutoEscape
	public String getPageKey();

	/**
	 * Sets the page key of this insta site images.
	 *
	 * @param pageKey the page key of this insta site images
	 */
	public void setPageKey(String pageKey);

	/**
	 * Returns the media url of this insta site images.
	 *
	 * @return the media url of this insta site images
	 */
	@AutoEscape
	public String getMediaUrl();

	/**
	 * Sets the media url of this insta site images.
	 *
	 * @param mediaUrl the media url of this insta site images
	 */
	public void setMediaUrl(String mediaUrl);

	/**
	 * Returns the instaimage url of this insta site images.
	 *
	 * @return the instaimage url of this insta site images
	 */
	@AutoEscape
	public String getInstaimageUrl();

	/**
	 * Sets the instaimage url of this insta site images.
	 *
	 * @param instaimageUrl the instaimage url of this insta site images
	 */
	public void setInstaimageUrl(String instaimageUrl);

	/**
	 * Returns the timestamp of this insta site images.
	 *
	 * @return the timestamp of this insta site images
	 */
	@AutoEscape
	public String getTimestamp();

	/**
	 * Sets the timestamp of this insta site images.
	 *
	 * @param timestamp the timestamp of this insta site images
	 */
	public void setTimestamp(String timestamp);

	/**
	 * Returns the other detid of this insta site images.
	 *
	 * @return the other detid of this insta site images
	 */
	public long getOtherDetid();

	/**
	 * Sets the other detid of this insta site images.
	 *
	 * @param otherDetid the other detid of this insta site images
	 */
	public void setOtherDetid(long otherDetid);

}