/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jwc.insta.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InstaOtherDetails service. Represents a row in the &quot;JWC_InstaOtherDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>jwc.insta.model.impl.InstaOtherDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>jwc.insta.model.impl.InstaOtherDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InstaOtherDetails
 * @generated
 */
@ProviderType
public interface InstaOtherDetailsModel extends BaseModel<InstaOtherDetails> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a insta other details model instance should use the {@link InstaOtherDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this insta other details.
	 *
	 * @return the primary key of this insta other details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this insta other details.
	 *
	 * @param primaryKey the primary key of this insta other details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the other detid of this insta other details.
	 *
	 * @return the other detid of this insta other details
	 */
	public long getOtherDetid();

	/**
	 * Sets the other detid of this insta other details.
	 *
	 * @param otherDetid the other detid of this insta other details
	 */
	public void setOtherDetid(long otherDetid);

	/**
	 * Returns the insta handle name of this insta other details.
	 *
	 * @return the insta handle name of this insta other details
	 */
	@AutoEscape
	public String getInstaHandleName();

	/**
	 * Sets the insta handle name of this insta other details.
	 *
	 * @param instaHandleName the insta handle name of this insta other details
	 */
	public void setInstaHandleName(String instaHandleName);

	/**
	 * Returns the follow us link of this insta other details.
	 *
	 * @return the follow us link of this insta other details
	 */
	@AutoEscape
	public String getFollowUsLink();

	/**
	 * Sets the follow us link of this insta other details.
	 *
	 * @param followUsLink the follow us link of this insta other details
	 */
	public void setFollowUsLink(String followUsLink);

}