/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jwc.insta.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import jwc.insta.model.InstaOtherDetails;
import jwc.insta.model.InstaOtherDetailsModel;

/**
 * The base model implementation for the InstaOtherDetails service. Represents a row in the &quot;JWC_InstaOtherDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>InstaOtherDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InstaOtherDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InstaOtherDetailsImpl
 * @generated
 */
public class InstaOtherDetailsModelImpl
	extends BaseModelImpl<InstaOtherDetails> implements InstaOtherDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a insta other details model instance should use the <code>InstaOtherDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "JWC_InstaOtherDetails";

	public static final Object[][] TABLE_COLUMNS = {
		{"otherDetid", Types.BIGINT}, {"instaHandleName", Types.VARCHAR},
		{"followUsLink", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("otherDetid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("instaHandleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("followUsLink", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JWC_InstaOtherDetails (otherDetid LONG not null primary key,instaHandleName VARCHAR(75) null,followUsLink VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table JWC_InstaOtherDetails";

	public static final String ORDER_BY_JPQL =
		" ORDER BY instaOtherDetails.otherDetid ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JWC_InstaOtherDetails.otherDetid ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public InstaOtherDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _otherDetid;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOtherDetid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _otherDetid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return InstaOtherDetails.class;
	}

	@Override
	public String getModelClassName() {
		return InstaOtherDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<InstaOtherDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<InstaOtherDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InstaOtherDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((InstaOtherDetails)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<InstaOtherDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<InstaOtherDetails, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(InstaOtherDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<InstaOtherDetails, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<InstaOtherDetails, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, InstaOtherDetails>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			InstaOtherDetails.class.getClassLoader(), InstaOtherDetails.class,
			ModelWrapper.class);

		try {
			Constructor<InstaOtherDetails> constructor =
				(Constructor<InstaOtherDetails>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<InstaOtherDetails, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<InstaOtherDetails, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<InstaOtherDetails, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<InstaOtherDetails, Object>>();
		Map<String, BiConsumer<InstaOtherDetails, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<InstaOtherDetails, ?>>();

		attributeGetterFunctions.put(
			"otherDetid", InstaOtherDetails::getOtherDetid);
		attributeSetterBiConsumers.put(
			"otherDetid",
			(BiConsumer<InstaOtherDetails, Long>)
				InstaOtherDetails::setOtherDetid);
		attributeGetterFunctions.put(
			"instaHandleName", InstaOtherDetails::getInstaHandleName);
		attributeSetterBiConsumers.put(
			"instaHandleName",
			(BiConsumer<InstaOtherDetails, String>)
				InstaOtherDetails::setInstaHandleName);
		attributeGetterFunctions.put(
			"followUsLink", InstaOtherDetails::getFollowUsLink);
		attributeSetterBiConsumers.put(
			"followUsLink",
			(BiConsumer<InstaOtherDetails, String>)
				InstaOtherDetails::setFollowUsLink);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getOtherDetid() {
		return _otherDetid;
	}

	@Override
	public void setOtherDetid(long otherDetid) {
		_otherDetid = otherDetid;
	}

	@Override
	public String getInstaHandleName() {
		if (_instaHandleName == null) {
			return "";
		}
		else {
			return _instaHandleName;
		}
	}

	@Override
	public void setInstaHandleName(String instaHandleName) {
		_instaHandleName = instaHandleName;
	}

	@Override
	public String getFollowUsLink() {
		if (_followUsLink == null) {
			return "";
		}
		else {
			return _followUsLink;
		}
	}

	@Override
	public void setFollowUsLink(String followUsLink) {
		_followUsLink = followUsLink;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, InstaOtherDetails.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public InstaOtherDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, InstaOtherDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InstaOtherDetailsImpl instaOtherDetailsImpl =
			new InstaOtherDetailsImpl();

		instaOtherDetailsImpl.setOtherDetid(getOtherDetid());
		instaOtherDetailsImpl.setInstaHandleName(getInstaHandleName());
		instaOtherDetailsImpl.setFollowUsLink(getFollowUsLink());

		instaOtherDetailsImpl.resetOriginalValues();

		return instaOtherDetailsImpl;
	}

	@Override
	public int compareTo(InstaOtherDetails instaOtherDetails) {
		long primaryKey = instaOtherDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof InstaOtherDetails)) {
			return false;
		}

		InstaOtherDetails instaOtherDetails = (InstaOtherDetails)obj;

		long primaryKey = instaOtherDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<InstaOtherDetails> toCacheModel() {
		InstaOtherDetailsCacheModel instaOtherDetailsCacheModel =
			new InstaOtherDetailsCacheModel();

		instaOtherDetailsCacheModel.otherDetid = getOtherDetid();

		instaOtherDetailsCacheModel.instaHandleName = getInstaHandleName();

		String instaHandleName = instaOtherDetailsCacheModel.instaHandleName;

		if ((instaHandleName != null) && (instaHandleName.length() == 0)) {
			instaOtherDetailsCacheModel.instaHandleName = null;
		}

		instaOtherDetailsCacheModel.followUsLink = getFollowUsLink();

		String followUsLink = instaOtherDetailsCacheModel.followUsLink;

		if ((followUsLink != null) && (followUsLink.length() == 0)) {
			instaOtherDetailsCacheModel.followUsLink = null;
		}

		return instaOtherDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<InstaOtherDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<InstaOtherDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InstaOtherDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((InstaOtherDetails)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<InstaOtherDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<InstaOtherDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InstaOtherDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((InstaOtherDetails)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, InstaOtherDetails>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _otherDetid;
	private String _instaHandleName;
	private String _followUsLink;
	private InstaOtherDetails _escapedModel;

}