/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jwc.insta.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import jwc.insta.model.HandleAPIKeys;
import jwc.insta.service.HandleAPIKeysLocalService;
import jwc.insta.service.persistence.HandleAPIKeysPersistence;
import jwc.insta.service.persistence.InstaOtherDetailsPersistence;
import jwc.insta.service.persistence.InstaSiteImagesPersistence;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the handle api keys local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link jwc.insta.service.impl.HandleAPIKeysLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see jwc.insta.service.impl.HandleAPIKeysLocalServiceImpl
 * @generated
 */
public abstract class HandleAPIKeysLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, HandleAPIKeysLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>HandleAPIKeysLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>jwc.insta.service.HandleAPIKeysLocalServiceUtil</code>.
	 */

	/**
	 * Adds the handle api keys to the database. Also notifies the appropriate model listeners.
	 *
	 * @param handleAPIKeys the handle api keys
	 * @return the handle api keys that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public HandleAPIKeys addHandleAPIKeys(HandleAPIKeys handleAPIKeys) {
		handleAPIKeys.setNew(true);

		return handleAPIKeysPersistence.update(handleAPIKeys);
	}

	/**
	 * Creates a new handle api keys with the primary key. Does not add the handle api keys to the database.
	 *
	 * @param handleAPIKeyId the primary key for the new handle api keys
	 * @return the new handle api keys
	 */
	@Override
	@Transactional(enabled = false)
	public HandleAPIKeys createHandleAPIKeys(long handleAPIKeyId) {
		return handleAPIKeysPersistence.create(handleAPIKeyId);
	}

	/**
	 * Deletes the handle api keys with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param handleAPIKeyId the primary key of the handle api keys
	 * @return the handle api keys that was removed
	 * @throws PortalException if a handle api keys with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public HandleAPIKeys deleteHandleAPIKeys(long handleAPIKeyId)
		throws PortalException {

		return handleAPIKeysPersistence.remove(handleAPIKeyId);
	}

	/**
	 * Deletes the handle api keys from the database. Also notifies the appropriate model listeners.
	 *
	 * @param handleAPIKeys the handle api keys
	 * @return the handle api keys that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public HandleAPIKeys deleteHandleAPIKeys(HandleAPIKeys handleAPIKeys) {
		return handleAPIKeysPersistence.remove(handleAPIKeys);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			HandleAPIKeys.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return handleAPIKeysPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jwc.insta.model.impl.HandleAPIKeysModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return handleAPIKeysPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jwc.insta.model.impl.HandleAPIKeysModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return handleAPIKeysPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return handleAPIKeysPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return handleAPIKeysPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public HandleAPIKeys fetchHandleAPIKeys(long handleAPIKeyId) {
		return handleAPIKeysPersistence.fetchByPrimaryKey(handleAPIKeyId);
	}

	/**
	 * Returns the handle api keys with the primary key.
	 *
	 * @param handleAPIKeyId the primary key of the handle api keys
	 * @return the handle api keys
	 * @throws PortalException if a handle api keys with the primary key could not be found
	 */
	@Override
	public HandleAPIKeys getHandleAPIKeys(long handleAPIKeyId)
		throws PortalException {

		return handleAPIKeysPersistence.findByPrimaryKey(handleAPIKeyId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(handleAPIKeysLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(HandleAPIKeys.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("handleAPIKeyId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			handleAPIKeysLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(HandleAPIKeys.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"handleAPIKeyId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(handleAPIKeysLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(HandleAPIKeys.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("handleAPIKeyId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return handleAPIKeysPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return handleAPIKeysLocalService.deleteHandleAPIKeys(
			(HandleAPIKeys)persistedModel);
	}

	public BasePersistence<HandleAPIKeys> getBasePersistence() {
		return handleAPIKeysPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return handleAPIKeysPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the handle api keyses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jwc.insta.model.impl.HandleAPIKeysModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of handle api keyses
	 * @param end the upper bound of the range of handle api keyses (not inclusive)
	 * @return the range of handle api keyses
	 */
	@Override
	public List<HandleAPIKeys> getHandleAPIKeyses(int start, int end) {
		return handleAPIKeysPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of handle api keyses.
	 *
	 * @return the number of handle api keyses
	 */
	@Override
	public int getHandleAPIKeysesCount() {
		return handleAPIKeysPersistence.countAll();
	}

	/**
	 * Updates the handle api keys in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param handleAPIKeys the handle api keys
	 * @return the handle api keys that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public HandleAPIKeys updateHandleAPIKeys(HandleAPIKeys handleAPIKeys) {
		return handleAPIKeysPersistence.update(handleAPIKeys);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			HandleAPIKeysLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		handleAPIKeysLocalService = (HandleAPIKeysLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return HandleAPIKeysLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return HandleAPIKeys.class;
	}

	protected String getModelClassName() {
		return HandleAPIKeys.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = handleAPIKeysPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected HandleAPIKeysLocalService handleAPIKeysLocalService;

	@Reference
	protected HandleAPIKeysPersistence handleAPIKeysPersistence;

	@Reference
	protected InstaOtherDetailsPersistence instaOtherDetailsPersistence;

	@Reference
	protected InstaSiteImagesPersistence instaSiteImagesPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}