/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jwc.insta.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import jwc.insta.model.InstaSiteImages;
import jwc.insta.service.InstaSiteImagesLocalService;
import jwc.insta.service.persistence.HandleAPIKeysPersistence;
import jwc.insta.service.persistence.InstaOtherDetailsPersistence;
import jwc.insta.service.persistence.InstaSiteImagesPersistence;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the insta site images local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link jwc.insta.service.impl.InstaSiteImagesLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see jwc.insta.service.impl.InstaSiteImagesLocalServiceImpl
 * @generated
 */
public abstract class InstaSiteImagesLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   InstaSiteImagesLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>InstaSiteImagesLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>jwc.insta.service.InstaSiteImagesLocalServiceUtil</code>.
	 */

	/**
	 * Adds the insta site images to the database. Also notifies the appropriate model listeners.
	 *
	 * @param instaSiteImages the insta site images
	 * @return the insta site images that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public InstaSiteImages addInstaSiteImages(InstaSiteImages instaSiteImages) {
		instaSiteImages.setNew(true);

		return instaSiteImagesPersistence.update(instaSiteImages);
	}

	/**
	 * Creates a new insta site images with the primary key. Does not add the insta site images to the database.
	 *
	 * @param instaSiteImageId the primary key for the new insta site images
	 * @return the new insta site images
	 */
	@Override
	@Transactional(enabled = false)
	public InstaSiteImages createInstaSiteImages(long instaSiteImageId) {
		return instaSiteImagesPersistence.create(instaSiteImageId);
	}

	/**
	 * Deletes the insta site images with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param instaSiteImageId the primary key of the insta site images
	 * @return the insta site images that was removed
	 * @throws PortalException if a insta site images with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public InstaSiteImages deleteInstaSiteImages(long instaSiteImageId)
		throws PortalException {

		return instaSiteImagesPersistence.remove(instaSiteImageId);
	}

	/**
	 * Deletes the insta site images from the database. Also notifies the appropriate model listeners.
	 *
	 * @param instaSiteImages the insta site images
	 * @return the insta site images that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public InstaSiteImages deleteInstaSiteImages(
		InstaSiteImages instaSiteImages) {

		return instaSiteImagesPersistence.remove(instaSiteImages);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			InstaSiteImages.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return instaSiteImagesPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jwc.insta.model.impl.InstaSiteImagesModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return instaSiteImagesPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jwc.insta.model.impl.InstaSiteImagesModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return instaSiteImagesPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return instaSiteImagesPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return instaSiteImagesPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public InstaSiteImages fetchInstaSiteImages(long instaSiteImageId) {
		return instaSiteImagesPersistence.fetchByPrimaryKey(instaSiteImageId);
	}

	/**
	 * Returns the insta site images with the primary key.
	 *
	 * @param instaSiteImageId the primary key of the insta site images
	 * @return the insta site images
	 * @throws PortalException if a insta site images with the primary key could not be found
	 */
	@Override
	public InstaSiteImages getInstaSiteImages(long instaSiteImageId)
		throws PortalException {

		return instaSiteImagesPersistence.findByPrimaryKey(instaSiteImageId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(instaSiteImagesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(InstaSiteImages.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("instaSiteImageId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			instaSiteImagesLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(InstaSiteImages.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"instaSiteImageId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(instaSiteImagesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(InstaSiteImages.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("instaSiteImageId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return instaSiteImagesPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return instaSiteImagesLocalService.deleteInstaSiteImages(
			(InstaSiteImages)persistedModel);
	}

	public BasePersistence<InstaSiteImages> getBasePersistence() {
		return instaSiteImagesPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return instaSiteImagesPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the insta site imageses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jwc.insta.model.impl.InstaSiteImagesModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of insta site imageses
	 * @param end the upper bound of the range of insta site imageses (not inclusive)
	 * @return the range of insta site imageses
	 */
	@Override
	public List<InstaSiteImages> getInstaSiteImageses(int start, int end) {
		return instaSiteImagesPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of insta site imageses.
	 *
	 * @return the number of insta site imageses
	 */
	@Override
	public int getInstaSiteImagesesCount() {
		return instaSiteImagesPersistence.countAll();
	}

	/**
	 * Updates the insta site images in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param instaSiteImages the insta site images
	 * @return the insta site images that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public InstaSiteImages updateInstaSiteImages(
		InstaSiteImages instaSiteImages) {

		return instaSiteImagesPersistence.update(instaSiteImages);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			InstaSiteImagesLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		instaSiteImagesLocalService = (InstaSiteImagesLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return InstaSiteImagesLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return InstaSiteImages.class;
	}

	protected String getModelClassName() {
		return InstaSiteImages.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = instaSiteImagesPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected HandleAPIKeysPersistence handleAPIKeysPersistence;

	@Reference
	protected InstaOtherDetailsPersistence instaOtherDetailsPersistence;

	protected InstaSiteImagesLocalService instaSiteImagesLocalService;

	@Reference
	protected InstaSiteImagesPersistence instaSiteImagesPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}